config/routes.rb
Statr::Application.routes.draw do
  devise_for :users

  root :to => "dashboard#show"

  resource :dashboard, :controller => "dashboard", :only => :show
  resource :calendar,  :controller => "calendar",  :only => :show

  resources :categories,   :except => :show
  resources :transactions, :except => :show

  match "/calendar/:year/:month" => "calendar#show", :constraints => { :year => /\d{4}/, :month => /\d{2}/ }, :as => :calendar_for_month
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  has_many :transactions, :dependent => :destroy

  validates :name, :presence => true

  has_friendly_id :name, :use_slug => true, :scope => :user_id

  before_destroy do
    unless transactions.empty?
      errors.add :base, "Category is used in one or more transaction" 
      false
    end
  end

  def self.options_for_select
    Category.all.map { |c| [c.name, c.id] }
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :category

  validates :category,    :presence => true
  validates :executed_at, :presence => true
  validates :amount,      :presence => true

  default_value_for :executed_at, Date.today

  scope :incomings, joins(:category).where("categories.income = ?", true)
  scope :expenses, joins(:category).where("categories.income = ?", false)
  scope :for_month, lambda { |date|
    where(:executed_at => date.beginning_of_month..date.end_of_month)
  }
  scope :for_this_month, lambda { for_month(Time.zone.now) }

  def self.leftover_from(incomings, expenses)
    incomings - expenses
  end

  def self.leftover_for(transactions)
    transactions.inject(0) do |sum, transaction|
      if transaction.category.income?
        sum += transaction.amount 
      else
        sum -= transaction.amount 
      end
    end
  end

  def self.average_from(incomings, expenses)
    self.leftover_from(incomings, expenses) / 28
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :lockable

  has_many :categories,   :dependent => :destroy
  has_many :transactions, :through => :categories

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_date(year = nil, month = nil)
    return Time.zone.now if year.nil? || month.nil?

    Time.zone.local(year, month)
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_filter :authenticate_user!

  def show
    @transactions = current_user.transactions

    @date = current_date(params[:year], params[:month])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    respond_with @categories = current_user.categories
  end

  def new
    respond_with @category = Category.new
  end

  def create
    @category = current_user.categories.build params[:category]
    @category.save

    flash[:notice] = "Category created" unless @category.invalid?
    respond_with @category, :location => categories_path
  end

  def edit
    respond_with @category = current_user.categories.find(params[:id])
  end

  def update
    @category = current_user.categories.find params[:id]
    @category.update_attributes params[:category]
    
    flash[:notice] = "Category updated" unless @category.invalid?
    respond_with @category, :location => categories_path
  end

  def destroy
    @category = current_user.categories.find params[:id]
    @category.destroy

    flash[:notice] = @category.errors.empty? ? "Category destroyed" : @category.errors.full_messages.first 
    respond_with @category, :location => categories_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def show
    @transactions = current_user.transactions.order("executed_at DESC").limit(10)
    @income_this_month = current_user.transactions.for_this_month.incomings.sum(:amount)
    @expenses_this_month = current_user.transactions.for_this_month.expenses.sum(:amount)

    @leftover = Transaction.leftover_from(@income_this_month, @expenses_this_month)
    @average = Transaction.average_from(@income_this_month, @expenses_this_month)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    respond_with @transactions = current_user.transactions
  end

  def new
    respond_with @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new params[:transaction]
    @transaction.save

    flash[:notice] = "Transaction created" unless @transaction.invalid?
    respond_with @transaction, :location => params[:continue].nil? ? new_transaction_path : transactions_path
  end

  def edit
    respond_with @transaction = current_user.transactions.find(params[:id])
  end

  def update
    @transaction = current_user.transactions.find params[:id], :readonly => false
    @transaction.update_attributes params[:transaction]

    flash[:notice] = "Transaction updated" unless @transaction.invalid?
    respond_with @transaction, :location => transactions_path
  end

  def destroy
    @transaction = current_user.transactions.find params[:id]
    @transaction.destroy

    flash[:notice] = "Transaction destroyed"
    respond_with @transaction
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def previous_calendar_path(date)
    date = date.beginning_of_month - 1
    month_path(date)
  end

  def next_calendar_path(date)
    date = date.end_of_month + 1
    month_path(date)
  end

  protected

  def month_path(date)
    calendar_for_month_path(date.year, "%02d" % date.month)
  end
end

app/views/calendar/show.html.erb
<h1>Calendar</h1>

<div id="calendar">  
  <h2 id="month">  
    <%= link_to raw("&larr;"), previous_calendar_path(@date) %>
    <%= h @date.strftime("%B %Y") %>  
    <%= link_to raw("&rarr;"), next_calendar_path(@date) %>
  </h2>   
  <% calendar_for @transactions, :year => @date.year, :month => @date.month do |calendar| %>  
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')%>
    <% calendar.day(:day_method => :executed_at) do |date, transactions| %>  
      <% if transactions.count > 0 %>
        <span><%= number_to_currency Transaction.leftover_for(transactions) %></span>
      <% end %>
      <%= date.day %>  
      <ul>  
        <% transactions.each do |transaction| %>  
          <li class="<%= transaction.category.income? ? "income" : "expense" %>"><%= link_to "#{transaction.category.name} (#{number_to_currency transaction.amount})", edit_transaction_path(transaction) %></li>  
        <% end %>  
      </ul>
    <% end %>  
  <% end %>  
</div>

app/views/categories/_form.html.erb
<%= form_for category do |f|%>
  <% if category.errors.any? %>
    <ul>
      <% category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>  

  <p><%= f.label :name %><br />
  <%= f.text_field :name %></p>

  <p><%= f.label :income %><br />
  <%= f.check_box :income %></p>

  <p><%= f.submit %></p>
<% end -%>

app/views/categories/edit.html.erb
<h2>Edit category</h2>

<%= render :partial => "form", :locals => { :category => @category } %>

app/views/categories/index.html.erb
<h2>List categories</h2>

<ul>
  <% @categories.each do |category| -%>
    <li><%= category.name %> (<%= link_to "edit", edit_category_path(category) %> - <%= link_to "remove", category, :method => :delete, :confirm => "Are you sure?" %>)</li>
  <% end -%>
</ul>

app/views/categories/new.html.erb
<h2>New category</h2>

<%= render :partial => "form", :locals => { :category => @category } %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>

<h2>Statistics for this month</h2>
<ul>
  <li><strong>Income: </strong><%= number_to_currency @income_this_month %></li>
  <li><strong>Expenses: </strong><%= number_to_currency @expenses_this_month %></li>
  <li><strong>Left: </strong><%= number_to_currency @leftover %></li>
  <li><strong>Spend/Day: </strong><%= number_to_currency @average %></li>
</ul>

<h2>Recent transaction</h2>
<ul>
  <% @transactions.each do |transaction| %>
    <li><%= render transaction %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Statr</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <ul>
    <li><%= link_to_unless_current "dashboard", dashboard_path %></li>
    <li><%= link_to_unless_current "calendar", calendar_path %></li>
    <li><%= link_to_unless_current "categories", categories_path %></li>
    <li><%= link_to_unless_current "transactions", transactions_path %></li>
  </ul>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for transaction do |f|%>
  <% if transaction.errors.any? %>
    <ul>
      <% transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>  

  <p><%= f.label :executed_at %><br />
  <%= f.text_field :executed_at %></p>

  <p><%= f.label :amount %><br />
<%= f.text_field :amount, :precision => 2, :delimiter => "" %></p>

  <p><%= f.label :category_id %><br />
  <%= f.select :category_id, Category.options_for_select, { :include_blank => true } %></p>

  <p><%= f.label :description %><br />
  <%= f.text_area :description %></p>

  <p><%= f.submit %><% if transaction.new_record? %><%= f.submit "Create transaction and continue", :name => "continue" %><% end %></p>
<% end -%>

app/views/transactions/_transaction.html.erb
<span><%= transaction.executed_at %></span>
<span><%= number_to_currency transaction.amount %></span>
<span><%= transaction.category.name %></span>
<span><%= transaction.description %></span>
<%= link_to "edit", edit_transaction_path(transaction) %>
<%= link_to "remove", transaction, :method => :delete, :confirm => "Are you sure?" %>

app/views/transactions/edit.html.erb
<h2>Edit transaction</h2>

<%= render :partial => "form", :locals => { :transaction => @transaction } %>

app/views/transactions/index.html.erb
<h2>List transactions</h2>

<ul>
  <% @transactions.each do |transaction| -%>
    <li><%= render transaction %></li>
  <% end -%>
</ul>

app/views/transactions/new.html.erb
<h2>New transaction</h2>

<%= render :partial => "form", :locals => { :transaction => @transaction } %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>